`timescale 1ns/1ps
// Generated by gen_nbit_arith.pl
// Mode: add
// 8-bit module: adder_8bit

module fulladder (
    input  wire a,
    input  wire b,
    input  wire cin,
    output wire sum,
    output wire cout
);
    // simple combinational full adder using arithmetic expression
    assign {cout, sum} = a + b + cin;
endmodule

module adder_8bit (
    input  wire [8-1:0] a,
    input  wire [8-1:0] b,
    input  wire           cin,
    output wire [8-1:0] sum,
    output wire           cout
);
    wire [8-1:0] carry;

    // bit 0
    fulladder fa0 (
        .a(a[0]),
        .b(b[0]),
        .cin(cin),
        .sum(sum[0]),
        .cout(carry[0])
    );

    // bit 1
    fulladder fa1 (
        .a(a[1]),
        .b(b[1]),
        .cin(carry[0]),
        .sum(sum[1]),
        .cout(carry[1])
    );

    // bit 2
    fulladder fa2 (
        .a(a[2]),
        .b(b[2]),
        .cin(carry[1]),
        .sum(sum[2]),
        .cout(carry[2])
    );

    // bit 3
    fulladder fa3 (
        .a(a[3]),
        .b(b[3]),
        .cin(carry[2]),
        .sum(sum[3]),
        .cout(carry[3])
    );

    // bit 4
    fulladder fa4 (
        .a(a[4]),
        .b(b[4]),
        .cin(carry[3]),
        .sum(sum[4]),
        .cout(carry[4])
    );

    // bit 5
    fulladder fa5 (
        .a(a[5]),
        .b(b[5]),
        .cin(carry[4]),
        .sum(sum[5]),
        .cout(carry[5])
    );

    // bit 6
    fulladder fa6 (
        .a(a[6]),
        .b(b[6]),
        .cin(carry[5]),
        .sum(sum[6]),
        .cout(carry[6])
    );

    // bit 7
    fulladder fa7 (
        .a(a[7]),
        .b(b[7]),
        .cin(carry[6]),
        .sum(sum[7]),
        .cout(carry[7])
    );

    assign cout = carry[8-1];
endmodule

